POST https://test-fe.mysellerpintar.com/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNTBlOTQxOS05MWZkLTQzNTUtYmIwOS0xZjgwMjNmYzkwNjIiLCJpYXQiOjE3NDY2Mzk3MzF9.qK3lD3cw5RdVXBKRf7ZVx9cz7R5fdsBlb-WYEFyHdrI
Content-Type: application/json

{
    "title": "test-post",
    "content": "test123",
    "categoryId": "779a2f5e-454f-4ef5-af1e-b3366ab754f2"
}

###
POST https://test-fe.mysellerpintar.com/api/login
Content-Type: application/json

{
    "username": "Muhamad Yoga"
    "password": "yogacahaya123"
}

###
GET https://test-fe.mysellerpintar.com/api/categories?name=funtesting
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjMmNmZDYyYy0xMzJjLTQ0OTQtODg4Ny02ODNiMzQ0NTI0ZDAiLCJpYXQiOjE3NDY4NzkyMjl9.fRe6YCvveD8nTFgNMqtExPyZcP0YsyFy5CKvkf-5aig